// This code was generated by Hypar.
// Edits to this code will be overwritten the next time you run 'hypar init'.
// DO NOT EDIT THIS FILE.

using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Hypar.Functions;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Collections.Generic;

namespace OpenOfficeLayout
{
    public class OpenOfficeLayoutOutputs: ResultsBase
    {
		/// <summary>
		/// The number of desks.
		/// </summary>
		[JsonProperty("Total Desk Count")]
		public double TotalDeskCount {get;}



        /// <summary>
        /// Construct a OpenOfficeLayoutOutputs with default inputs.
        /// This should be used for testing only.
        /// </summary>
        public OpenOfficeLayoutOutputs() : base()
        {

        }


        /// <summary>
        /// Construct a OpenOfficeLayoutOutputs specifying all inputs.
        /// </summary>
        /// <returns></returns>
        [JsonConstructor]
        public OpenOfficeLayoutOutputs(double totalDeskCount): base()
        {
			this.TotalDeskCount = totalDeskCount;

		}

		public override string ToString()
		{
			var json = JsonConvert.SerializeObject(this);
			return json;
		}
	}
}