// This code was generated by Hypar.
// Edits to this code will be overwritten the next time you run 'hypar init'.
// DO NOT EDIT THIS FILE.

using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Hypar.Functions;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Collections.Generic;

namespace WorkplaceMetrics
{
    public class WorkplaceMetricsOutputs: ResultsBase
    {
		/// <summary>
		/// The total usable floor area of the project.
		/// </summary>
		[JsonProperty("Total Usable Floor Area")]
		public double TotalUsableFloorArea {get;}

		/// <summary>
		/// The usable floor area per person.
		/// </summary>
		[JsonProperty("Area per Person")]
		public double AreaPerPerson {get;}

		/// <summary>
		/// The total number of desks.
		/// </summary>
		[JsonProperty("Total Desk Count")]
		public double TotalDeskCount {get;}

		/// <summary>
		/// The total number of seats in the meeting rooms.
		/// </summary>
		[JsonProperty("Meeting room seats")]
		public double MeetingRoomSeats {get;}

		/// <summary>
		/// The total number of employees and visitors accommodated.
		/// </summary>
		[JsonProperty("Total Headcount")]
		public double TotalHeadcount {get;}

		/// <summary>
		/// The usable floor area per desk.
		/// </summary>
		[JsonProperty("Area per Desk")]
		public double AreaPerDesk {get;}

		/// <summary>
		/// How many people are there for each desk?
		/// </summary>
		[JsonProperty("Desk Sharing Ratio")]
		public double DeskSharingRatio {get;}

		/// <summary>
		/// On average how many people does each meeting room serve? A value of 30 means there's one meeting room for every 30 people.
		/// </summary>
		[JsonProperty("Meeting room ratio")]
		public double MeetingRoomRatio {get;}



        /// <summary>
        /// Construct a WorkplaceMetricsOutputs with default inputs.
        /// This should be used for testing only.
        /// </summary>
        public WorkplaceMetricsOutputs() : base()
        {

        }


        /// <summary>
        /// Construct a WorkplaceMetricsOutputs specifying all inputs.
        /// </summary>
        /// <returns></returns>
        [JsonConstructor]
        public WorkplaceMetricsOutputs(double totalUsableFloorArea, double areaPerPerson, double totalDeskCount, double meetingRoomSeats, double totalHeadcount, double areaPerDesk, double deskSharingRatio, double meetingRoomRatio): base()
        {
			this.TotalUsableFloorArea = totalUsableFloorArea;
			this.AreaPerPerson = areaPerPerson;
			this.TotalDeskCount = totalDeskCount;
			this.MeetingRoomSeats = meetingRoomSeats;
			this.TotalHeadcount = totalHeadcount;
			this.AreaPerDesk = areaPerDesk;
			this.DeskSharingRatio = deskSharingRatio;
			this.MeetingRoomRatio = meetingRoomRatio;

		}

		public override string ToString()
		{
			var json = JsonConvert.SerializeObject(this);
			return json;
		}
	}
}