// This code was generated by Hypar.
// Edits to this code will be overwritten the next time you run 'hypar init'.
// DO NOT EDIT THIS FILE.

using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Elements.Geometry.Solids;
using Elements.Validators;
using Elements.Serialization.JSON;
using Hypar.Functions;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using Hypar.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using Line = Elements.Geometry.Line;
using Polygon = Elements.Geometry.Polygon;

namespace DataHallLayout
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.1.21.0 (Newtonsoft.Json v13.0.0.0)")]
    
    public  class DataHallLayoutInputs : S3Args
    
    {
        [Newtonsoft.Json.JsonConstructor]
        
        public DataHallLayoutInputs(DataHallLayoutInputsCabinetDepth @cabinetDepth, DataHallLayoutInputsCabinetHeight @cabinetHeight, double @kWRack, double @hotAisleWidth, double @coldAisleWidth, double @clearance, bool @flipDirection, bool @swapColdHotPattern, string bucketName, string uploadsBucket, Dictionary<string, string> modelInputKeys, string gltfKey, string elementsKey, string ifcKey):
        base(bucketName, uploadsBucket, modelInputKeys, gltfKey, elementsKey, ifcKey)
        {
            var validator = Validator.Instance.GetFirstValidatorForType<DataHallLayoutInputs>();
            if(validator != null)
            {
                validator.PreConstruct(new object[]{ @cabinetDepth, @cabinetHeight, @kWRack, @hotAisleWidth, @coldAisleWidth, @clearance, @flipDirection, @swapColdHotPattern});
            }
        
            this.CabinetDepth = @cabinetDepth;
            this.CabinetHeight = @cabinetHeight;
            this.KWRack = @kWRack;
            this.HotAisleWidth = @hotAisleWidth;
            this.ColdAisleWidth = @coldAisleWidth;
            this.Clearance = @clearance;
            this.FlipDirection = @flipDirection;
            this.SwapColdHotPattern = @swapColdHotPattern;
        
            if(validator != null)
            {
                validator.PostConstruct(this);
            }
        }
    
        [Newtonsoft.Json.JsonProperty("Cabinet Depth", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public DataHallLayoutInputsCabinetDepth CabinetDepth { get; set; } = DataHallLayoutInputsCabinetDepth._1000mm;
    
        [Newtonsoft.Json.JsonProperty("Cabinet Height", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public DataHallLayoutInputsCabinetHeight CabinetHeight { get; set; } = DataHallLayoutInputsCabinetHeight._42U__2013mm_;
    
        [Newtonsoft.Json.JsonProperty("KW / Rack", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Range(5D, 30D)]
        public double KWRack { get; set; } = 10D;
    
        /// <summary>The width of each hot aisle.</summary>
        [Newtonsoft.Json.JsonProperty("Hot Aisle Width", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Range(0.0D, 4D)]
        public double HotAisleWidth { get; set; } = 0.9144D;
    
        /// <summary>The width of each cold aisle.</summary>
        [Newtonsoft.Json.JsonProperty("Cold Aisle Width", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Range(0.0D, 4D)]
        public double ColdAisleWidth { get; set; } = 1.2192D;
    
        /// <summary>The clearance around the perimeter of the Data Hall.</summary>
        [Newtonsoft.Json.JsonProperty("Clearance", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Range(0.0D, 4D)]
        public double Clearance { get; set; } = 1.2192D;
    
        /// <summary>Flip the direction of the layout.</summary>
        [Newtonsoft.Json.JsonProperty("Flip Direction", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public bool FlipDirection { get; set; } = false;
    
        /// <summary>Swap the cold/hot aisle pattern.</summary>
        [Newtonsoft.Json.JsonProperty("Swap Cold/Hot Pattern", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public bool SwapColdHotPattern { get; set; } = false;
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.1.21.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum DataHallLayoutInputsCabinetDepth
    {
        [System.Runtime.Serialization.EnumMember(Value = @"1000mm")]
        _1000mm = 0,
    
        [System.Runtime.Serialization.EnumMember(Value = @"1200mm")]
        _1200mm = 1,
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.1.21.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum DataHallLayoutInputsCabinetHeight
    {
        [System.Runtime.Serialization.EnumMember(Value = @"42U (2013mm)")]
        _42U__2013mm_ = 0,
    
        [System.Runtime.Serialization.EnumMember(Value = @"45U (2146mm)")]
        _45U__2146mm_ = 1,
    
        [System.Runtime.Serialization.EnumMember(Value = @"48U (2280mm)")]
        _48U__2280mm_ = 2,
    
    }
}