// This code was generated by Hypar.
// Edits to this code will be overwritten the next time you run 'hypar init'.
// DO NOT EDIT THIS FILE.

using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Hypar.Functions;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Collections.Generic;

namespace WallsLOD200
{
    public class WallsLOD200Outputs: SystemResults
    {

        /// <summary>
        /// Construct a WallsLOD200Outputs with default inputs.
        /// This should be used for testing only.
        /// </summary>
        public WallsLOD200Outputs() : base()
        {
        }

	}
}