//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.1.21.0 (Newtonsoft.Json v12.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------
using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Elements.Geometry.Solids;
using Elements.Spatial;
using Elements.Validators;
using Elements.Serialization.JSON;
using System;
using System.Collections.Generic;
using System.Linq;
using Line = Elements.Geometry.Line;
using Polygon = Elements.Geometry.Polygon;

namespace Elements
{
    #pragma warning disable // Disable all warnings

    /// <summary>Represents a set of program requirements and their desired adjacencies.</summary>
    [Newtonsoft.Json.JsonConverter(typeof(Elements.Serialization.JSON.JsonInheritanceConverter), "discriminator")]
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.1.21.0 (Newtonsoft.Json v12.0.0.0)")]
    public partial class ProgramAdjacencyMatrix : Element
    {
        [Newtonsoft.Json.JsonConstructor]
        public ProgramAdjacencyMatrix(IList<ProgramRequirement> @nodes, IList<Adjacency> @edges, System.Guid @id = default, string @name = null)
            : base(id, name)
        {
            this.Nodes = @nodes;
            this.Edges = @edges;
            }
        
        // Empty constructor
        public ProgramAdjacencyMatrix()
            : base()
        {
        }
    
        [Newtonsoft.Json.JsonProperty("Nodes", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public IList<ProgramRequirement> Nodes { get; set; }
    
        [Newtonsoft.Json.JsonProperty("Edges", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public IList<Adjacency> Edges { get; set; }
    
    
    }
}