// This code was generated by Hypar.
// Edits to this code will be overwritten the next time you run 'hypar init'.
// DO NOT EDIT THIS FILE.

using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Hypar.Functions;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Collections.Generic;

namespace MeetingRoomLayout
{
    public class MeetingRoomLayoutOutputs: ResultsBase
    {
		/// <summary>
		/// Total Seat Count
		/// </summary>
		[JsonProperty("Total Seat Count")]
		public double TotalSeatCount {get;}



        /// <summary>
        /// Construct a MeetingRoomLayoutOutputs with default inputs.
        /// This should be used for testing only.
        /// </summary>
        public MeetingRoomLayoutOutputs() : base()
        {

        }


        /// <summary>
        /// Construct a MeetingRoomLayoutOutputs specifying all inputs.
        /// </summary>
        /// <returns></returns>
        [JsonConstructor]
        public MeetingRoomLayoutOutputs(double totalSeatCount): base()
        {
			this.TotalSeatCount = totalSeatCount;

		}

		public override string ToString()
		{
			var json = JsonConvert.SerializeObject(this);
			return json;
		}
	}
}