#!/bin/bash
cd ClassroomLayout
hypar publish
cd ../DataHall
hypar publish
cd ../LoungeLayout
hypar publish
cd ../MeetingRoomLayout
hypar publish
cd ../OpenCollabLayout
hypar publish
cd ../OpenOfficeLayout
hypar publish
cd ../PantryLayout
hypar publish
cd ../PhoneBoothLayout
hypar publish
cd ../PrivateOfficeLayout
hypar publish
cd ../ReceptionLayout
hypar publish